from app.services.response_agent import response_agent
from app.services.incident_service import incident_service
from app.services.risk_service import risk_service
from app.services.threat_escalation_service import threat_escalation_service;


class EndpointService:

    def __init__(self):
        self.latest_analysis = None

    def analyze_telemetry(self, telemetry: dict):
        """
        Analyze telemetry received from the Endpoint Agent.
        """

        # ===================================
        # Extract telemetry sections
        # ===================================

        process_data = telemetry.get(
            "process_monitor", {}
        )

        network_data = telemetry.get(
            "network_monitor", {}
        )

        system_data = telemetry.get(
            "system_monitor", {}
        )

        file_data = telemetry.get(
            "file_monitor", {}
        )

        endpoint_info = telemetry.get(
            "endpoint_info", {}
        )

        # ===================================
        # Extract suspicious activity
        # ===================================

        suspicious_process_data = process_data.get(
            "suspicious_processes", {}
        )

        suspicious_connection_data = network_data.get(
            "suspicious_connections", {}
        )

        suspicious_processes = suspicious_process_data.get(
            "total_suspicious_processes", 0
        )

        suspicious_process_list = suspicious_process_data.get(
            "suspicious_processes", []
        )

        suspicious_connections = suspicious_connection_data.get(
            "total_suspicious_connections", 0
        )

        suspicious_connection_list = suspicious_connection_data.get(
            "suspicious_connections", []
        )

        suspicious_file_events = file_data.get(
            "total_suspicious_file_events", 0
        )

        system_anomaly_score = system_data.get(
            "anomaly_score", 0
        )

        # ===================================
        # FEATURE EXTRACTION
        # Convert telemetry into normalized
        # security scores between 0 and 1
        # ===================================


        # -----------------------------------
        # 1. Threat Probability
        # Based on suspicious processes
        # -----------------------------------

        threat_probability = 0.0

        if suspicious_process_list:

            total_process_score = sum(
                process.get("suspicion_score", 0)
                for process in suspicious_process_list
            )

            # Normalize based on number
            # and severity of suspicious processes
            threat_probability = min(
                total_process_score /
                max(len(suspicious_process_list), 1),
                1.0
            )


        # -----------------------------------
        # 2. Behaviour Score
        # Based on suspicious network activity
        # -----------------------------------

        behaviour_score = 0.0

        if suspicious_connection_list:

            behaviour_score = min(
                suspicious_connections * 0.25,
                1.0
            )


        # -----------------------------------
        # 3. IOC Score
        # Based on suspicious file events
        # -----------------------------------

        ioc_score = 0.0

        if suspicious_file_events > 0:

            ioc_score = min(
                suspicious_file_events * 0.20,
                1.0
            )


        # -----------------------------------
        # 4. Anomaly Score
        # Already generated by system monitor
        # -----------------------------------

        anomaly_score = min(
            float(system_anomaly_score),
            1.0
        )


        # -----------------------------------
        # 5. Temporal Score
        # Future enhancement
        # -----------------------------------

        temporal_score = 0.0


        # -----------------------------------
        # 6. Correlation Score
        # Future enhancement
        # -----------------------------------

        correlation_score = 0.0


        # ===================================
        # FINAL RISK CALCULATION
        # ===================================

        risk_result = risk_service.calculate_risk(

            threat_probability=threat_probability,

            anomaly_score=anomaly_score,

            behaviour_score=behaviour_score,

            ioc_score=ioc_score,

            temporal_score=temporal_score,

            correlation_score=correlation_score
        )


        risk_score = risk_result["risk_score"]

        severity = risk_result["severity"]


        # ===================================
        # RISK BREAKDOWN
        # Used by Dashboard
        # ===================================

        risk_breakdown = {

            "process_risk": round(
                threat_probability * 35,
                2
            ),

            "network_risk": round(
                behaviour_score * 15,
                2
            ),

            "file_risk": round(
                ioc_score * 15,
                2
            ),

            "system_risk": round(
                anomaly_score * 20,
                2
            )
        }


        # ===================================
        # RISK REASONS
        # ===================================

        risk_reasons = []

        if suspicious_processes > 0:

            risk_reasons.append(
                f"{suspicious_processes} suspicious process(es) "
                f"detected contributing "
                f"{risk_breakdown['process_risk']} risk points"
            )


        if suspicious_connections > 0:

            risk_reasons.append(
                f"{suspicious_connections} suspicious network "
                f"connection(s) detected contributing "
                f"{risk_breakdown['network_risk']} risk points"
            )


        if suspicious_file_events > 0:

            risk_reasons.append(
                f"{suspicious_file_events} suspicious file "
                f"event(s) detected contributing "
                f"{risk_breakdown['file_risk']} risk points"
            )


        if anomaly_score > 0:

            risk_reasons.append(
                "System resource anomaly detected "
                f"contributing "
                f"{risk_breakdown['system_risk']} risk points"
            )
        escalation_result = (
        threat_escalation_service.escalate_threat(

            risk_score=risk_score,

            severity=severity,

            suspicious_processes=
                suspicious_process_list,

            suspicious_connections=
                suspicious_connections,

            suspicious_file_events=
                suspicious_file_events,

            system_anomaly_score=
                anomaly_score
        )
    )
        risk_score = escalation_result["risk_score"]

        severity = escalation_result["severity"]


        # Add escalation reasons

        risk_reasons.extend(
            escalation_result.get(
                "escalation_reasons",
                []
            )
        )


        # ===================================
        # RESPONSE DECISION
        # ===================================

        response_result = response_agent.determine_response(

            risk_result={
                "severity": severity,
                "risk_score": risk_score
            },

            correlation_result={
                "correlation_score": correlation_score
            },

            ioc_result={
                "ioc_score": ioc_score
            }
        )


        # ===================================
        # ADD TARGET PROCESS
        # For automated response
        # ===================================

        response_command = response_result.get(
            "response_command"
        )

        if response_command and suspicious_process_list:

        # For CRITICAL response, prefer the validated
        # controlled critical test process
            critical_processes = [
                process
                for process in suspicious_process_list
                if process.get(
                    "controlled_critical_test",
                    False
                )
            ]

        if critical_processes:

            target_process = critical_processes[0]

        else:

            # Otherwise select highest suspicious process
            target_process = max(
                suspicious_process_list,
                key=lambda process:
                process.get(
                    "suspicion_score", 0
                )
            )

        response_command["target_pid"] = (
            target_process.get("pid")
        )

        response_command["target_process"] = (
            target_process.get("name")
        )


        # ===================================
        # INCIDENT CREATION
        # ===================================

        incident_result = incident_service.create_incident(

            risk_result={
                "severity": severity,
                "risk_score": risk_score
            },

            response_result=response_result,

            analysis_result={
                "threat_probability": threat_probability,
                "anomaly_score": anomaly_score,
                "behaviour_score": behaviour_score,
                "ioc_score": ioc_score
            }
        )


        # ===================================
        # FINAL ANALYSIS RESULT
        # ===================================

        result = {

            "endpoint_info": endpoint_info,

            "risk_score": risk_score,

            "severity": severity,
            "threat_escalation": escalation_result,

            "risk_reasons": risk_reasons,

            "risk_breakdown": risk_breakdown,

            "risk_factors": risk_result.get(
                "risk_factors", {}
            ),

            "risk_contributors": {

                "suspicious_processes":
                    suspicious_process_list,

                "suspicious_connections":
                    suspicious_connection_list,

                "suspicious_file_events":
                    file_data,

                "system_anomaly": {

                    "anomaly_detected":
                        system_data.get(
                            "anomaly_detected",
                            False
                        ),

                    "anomaly_score":
                        system_anomaly_score
                }
            },

            "telemetry_timestamp": telemetry.get(
                "timestamp"
            ),

            "response_decision": response_result,

            "incident": incident_result
        }


        # Store latest analysis
        self.latest_analysis = result

        return result


    def get_latest_analysis(self):
        return self.latest_analysis


endpoint_service = EndpointService()